// code/04_React18_SSR/05_react18_ssr_router/src/App.jsx
import React, { memo, useState } from "react";
import { useRoutes, Link } from "react-router-dom";
import routes from "./router";

const App = memo(() => {
  const [counter, setCounter] = useState(0);

  const increment = () => {
    setCounter(counter + 1);
  };

  return (
    <div>
      <h2>merge page</h2>
      <h2>{counter}</h2>
      <button onClick={increment}>+1</button>
      <Link to="/">home</Link>
      <Link to="/about">about</Link>

      {useRoutes(routes)}
    </div>
  );
});

export default App;

// code/01_vue3-SSR/05_vue3_ssr_vuerouter/src/App.vue
<template>
  <div>
    <h2>嘿嘿嘿</h2>
    <h2>{{ count }}</h2>
    <button @click="count++">+1</button>
    <router-link to="/home">home</router-link>
    <router-link to="/about">about</router-link>
    <router-view></router-view>
  </div>
</template>

<script setup>
import { ref } from 'vue'
const count = ref(0)
</script>
